#list of Coordinates of the top left corner, bottom_right corner and middle point of each bounding boxes. 
#For example, element 0 is the left corner of the first bounding box, element 1 is the bottom right corner, and element 2 is the middle point of the first bounding box.
# Similarly, element 3 is the top left corner of the second bounding box, and so on. 

person_tracking_msgs/Box[] bounding_boxes    
 




