# Middle of the box around the person to track (between 0 and 1)
person_tracked/PointMsg middle_point    

# Normalized value of the diagonal between the top left and bottom right corner of the bounding box around the target individual
float32 bounding_box_size    
           
#person_tracked/PointMsg left_hand_point   #point at the middle of the fist of the left hand
#person_tracked/PointMsg right_hand_point  #point at the middle of the fist of the right hand
#float32 radius                        #Error margin around the middlepoint

