person_detector_node:
  ros__parameters:
    standalone: true
    minimum_prob: 0.3
    
pilot_person_selector_node:
  ros__parameters:
    standalone: true

person_tracker_node:
  ros__parameters:
    standalone: true

pilot_person_drawer_node:
  ros__parameters:
    standalone: true

test:
  ros__parameters:
    standalone: true
